### ISSUE TITLE
`--version` option returns `CURRENT` instead of version

### ISSUE THREAD

**Issue by gregor-j** [ivanilves/lstags#212] opened 2020-01-02 07:48 UTC
```bash
$ lstags --version
VERSION: CURRENT
```

**Comment by ivanilves** [comment] 2020-01-11 22:35
Have you built it from source?

It will be always "CURRENT" when not running a binary release downloaded from GitHub.

**Comment by ivanilves** [comment] 2020-01-21 14:46
OK, probably you built this from source with `go build` not with release process and that's why you got "CURRENT". This is not a bug, closing this, be sure to reopen if you have any doubt 😉

**Comment by gregor-j** [comment] 2020-02-04 11:40
Sorry for my late response: No, I haven't built it from source, I downloaded the linux version from your GitHub release page: https://github.com/ivanilves/lstags/releases/tag/v1.2.12

```sh
$ wget "https://github.com/ivanilves/lstags/releases/download/v1.2.12/lstags-linux-v1.2.12.tar.gz"
$ tar xzf lstags-linux-v1.2.12.tar.gz 
$ ./lstags --version
VERSION: CURRENT
```

**Comment by ivanilves** [comment] 2020-02-06 15:47
You are right! Reopening. Will fix it.

**Comment by ivanilves** [comment] 2020-04-05 09:17
Hi, thanks for reporting this, officially fixed in https://github.com/ivanilves/lstags/releases/tag/v1.2.15

**Closed by ivanilves** 2020-04-05 09:17 UTC
Labels: handicap
